name: Build Scan Push
on:
 push:
  branches: [main]

env:
  IMAGE_NAME: ${{ secrets.DOCKERHUB_REPO }}


jobs:
  build:
      runs-on: windows-latest

steps:
  - name:checkout code
    uses: actions/checkout@v4

  - name:Login to DockerHub
    uses: docker/login-action@v2
    with:
	username:saiyada
	password:dckr_pat_SLyrEagV7ybWguMibJiVu46m87Q
 
  - name: Build DOCKER IMAGE
    run: docker build -t hello-devopssha256:0e9282ce2d7ec9465981756cb710e619b204e9c0
  - name: Run Trivy Scan
    uses: aquasecurity/trivy-action@v2
    with: 
      image-ref: $ docker hub secrets:0e9282ce2d7ec9465981756cb710e619b204e9c0
      exit code: '1'
      serverity: 'High,Critical'

 - name: push to DockerHub
   run: | docker tag hello-devops:0e9282ce2d7ec9465981756cb710e619b204e9c0
$env: IMAGE_NAME:latest
      docker push
$env: hello-devops:0e9282ce2d7ec9465981756cb710e619b204e9c0
docker push
$env: hello-devops:LATEST
  
 	



 
 	



